import json
import urllib.request

SUPABASE_URL = 'https://kayjrplfpvxcqynznnwn.supabase.co'
SERVICE_ROLE = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtheWpycGxmcHZ4Y3F5bnpubnduIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTExNjM0NiwiZXhwIjoyMDk2NjkyMzQ2fQ.uBMPG4wV4ngg7CaBRao14Tx8TNpi74JeZwBPJ_Pldc8'

sql = """
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  nombre_producto text not null,
  codigo text,
  categoria text,
  precio numeric not null default 0,
  stock integer not null default 0,
  estado text default 'Disponible',
  imagen text,
  descripcion text,
  observaciones text,
  marca text,
  talla text,
  fecha_alta date
);
"""

req = urllib.request.Request(
    f'{SUPABASE_URL}/rest/v1/sql',
    data=json.dumps({'sql': sql}).encode('utf-8'),
    headers={
        'Content-Type': 'application/json',
        'apikey': SERVICE_ROLE,
        'Authorization': f'Bearer {SERVICE_ROLE}',
    },
    method='POST'
)

try:
    with urllib.request.urlopen(req) as resp:
        print('STATUS', resp.status)
        print('BODY', resp.read().decode('utf-8'))
except Exception as exc:
    import traceback
    traceback.print_exc()
